package olahraga;

/**
 *
 * @author 0CIL650
 */
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frm_input_akun extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form frm_input_akun
     */
    
    koneksi koneksi1 = new koneksi();
    
     public frm_input_akun() {
        initComponents();
        String[] field={"no_akun2","nama_akun2","no_akun1"};
        model = new DefaultTableModel(field, 0);
        tabel_akun.setModel(model);
        tampil();
    }
    
    public void clear(){
        text_noakun2.setText("");
        text_namaakun2.setText("");
        text_noakun1.setText("");

    }
    
    public void hapus(){
        int pilih = JOptionPane.showConfirmDialog(null, "YAKIN ANDA MENGHAPUS?");
        if(pilih == JOptionPane.OK_OPTION)
            JOptionPane.showConfirmDialog(null, "DATA TELAH HILANG");
        else if(pilih == JOptionPane.NO_OPTION)
            JOptionPane.showConfirmDialog(null, "kok PHP?");
                
    }
    
    public void tampil(){
        DefaultTableModel table1=new DefaultTableModel();
        table1.addColumn("no_akun2");
        table1.addColumn("nama_akun2");
        table1.addColumn("no_akun1");


        tabel_akun.setModel(table1);
        try{
            ResultSet res = koneksi1.statement.executeQuery("Select * from akun");
            while(res.next()){
            table1.addRow(new Object[]{
                res.getString("no_akun2"),
                res.getString("nama_akun2"),
                res.getString("no_akun1"),

            });
            tabel_akun.setModel(table1);}
        }catch (Exception e){

       }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_noakun2 = new javax.swing.JTextField();
        text_namaakun2 = new javax.swing.JTextField();
        text_noakun1 = new javax.swing.JTextField();
        button_simpan = new javax.swing.JButton();
        button_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_akun = new javax.swing.JTable();
        button_back = new javax.swing.JButton();
        button_edit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NO AKUN 2");

        jLabel2.setText("NAMA AKUN 2");

        jLabel3.setText("NO AKUN 1");

        button_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        button_simpan.setText("SIMPAN");
        button_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_simpanActionPerformed(evt);
            }
        });

        button_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hapus.png"))); // NOI18N
        button_hapus.setText("HAPUS");
        button_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_hapusActionPerformed(evt);
            }
        });

        tabel_akun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_akun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_akunMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_akun);

        button_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kembali.png"))); // NOI18N
        button_back.setText("KEMBALI");
        button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backActionPerformed(evt);
            }
        });

        button_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        button_edit.setText("EDIT");
        button_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel4.setText("AKUN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1336, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_noakun1)
                            .addComponent(text_namaakun2)
                            .addComponent(text_noakun2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(button_hapus)
                                .addGap(18, 18, 18)
                                .addComponent(button_edit)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_simpan)
                                .addGap(72, 72, 72))))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(button_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_back)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_noakun2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(button_simpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(text_namaakun2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_noakun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_hapus)
                    .addComponent(button_edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_simpanActionPerformed
        // TODO add your handling code here:
        String no_akun2 = text_noakun2.getText();
        String nama_akun2 = text_namaakun2.getText();
        String no_akun1 = text_noakun1.getText();
        
        String SQL ="insert into akun(no_akun2, nama_akun2, no_akun1) values ('"+no_akun2+"','"+nama_akun2+"',"
                + "'"+no_akun1+"')";
        System.out.println(SQL);
        clear();
        tampil();
        
        
        try {
            koneksi1.statement.executeUpdate(SQL);
            tampil();
            JOptionPane.showMessageDialog(rootPane, "BERHASIL");
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "GAGAL");
        }
    }//GEN-LAST:event_button_simpanActionPerformed

    private void button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backActionPerformed
        // TODO add your handling code here:
         frm_utama n = new frm_utama();
        n.setVisible(true);
        this.setVisible(false); // agar form yang tampil 1=fals
    }//GEN-LAST:event_button_backActionPerformed

    private void button_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editActionPerformed
        // TODO add your handling code here:
        String no_akun2 = text_noakun2.getText();
        String nama_akun2 = text_namaakun2.getText();
        String no_akun1 = text_noakun1.getText();
        
        String SQL = "UPDATE akun SET "
                +"nama_akun2='"+text_namaakun2.getText()+"'"
                +"WHERE no_akun2='"+text_noakun2.getText()+"'";
        
        System.out.println(SQL);
        tampil();
        clear();
        try {
            koneksi1.statement.executeUpdate(SQL);
            tampil();
            JOptionPane.showMessageDialog(rootPane, "DATA AKUN BERHASIL GANTI");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, "DATA AKUN GAGAL DIGANTI");
        }
    }//GEN-LAST:event_button_editActionPerformed

    private void button_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_hapusActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Menghapus Data?","Delete",JOptionPane.YES_NO_OPTION );
        if (p==0){
        String no_akun2 = text_noakun2.getText();
        String nama_akun2 = text_namaakun2.getText();
        String no_akun1  = text_noakun1.getText();
     
        String SQL = "delete from akun where no_akun2='"+text_noakun2.getText()+"'";
        
        System.out.println(SQL);
        tampil();
        clear();
        
        try {
            koneksi1.statement.executeUpdate(SQL);
            tampil();
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_button_hapusActionPerformed

    private void tabel_akunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_akunMouseClicked
        // TODO add your handling code here:
        int table=tabel_akun.getSelectedRow();
     String a=tabel_akun.getValueAt(table, 0).toString();
     String b=tabel_akun.getValueAt(table, 1).toString();
     String c=tabel_akun.getValueAt(table, 2).toString();
     
     text_noakun2.setText(a);
     text_namaakun2.setText(b);
     text_noakun1.setText(c);
    }//GEN-LAST:event_tabel_akunMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_input_akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_input_akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_input_akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_input_akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_input_akun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_back;
    private javax.swing.JButton button_edit;
    private javax.swing.JButton button_hapus;
    private javax.swing.JButton button_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_akun;
    private javax.swing.JTextField text_namaakun2;
    private javax.swing.JTextField text_noakun1;
    private javax.swing.JTextField text_noakun2;
    // End of variables declaration//GEN-END:variables
}
