package olahraga;

import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 0CIL650
 */
public class frm_input_golongan extends javax.swing.JFrame {
    DefaultTableModel model;
    koneksi koneksi1 = new koneksi();
    
    public frm_input_golongan() {
        initComponents();
        String[] field={"no_akun1","nama_akun1","kd_posisi"};
        model = new DefaultTableModel(field, 0);
        tabel_golongan.setModel(model);
        tampil();
    }
    
    public void clear(){
        text_noakun1.setText("");
        text_namaakun1.setText("");
        text_kdposisi.setText("");
    }
    
    public void hapus(){
        int pilih = JOptionPane.showConfirmDialog(null, "APAKAH ANDA YAKIN MENGHAPUS DATA?");
        if(pilih == JOptionPane.OK_OPTION)
            JOptionPane.showConfirmDialog(null, "DATA TERHAPUSKAN");
        else if(pilih == JOptionPane.NO_OPTION)
            JOptionPane.showConfirmDialog(null, "SILAHKAN?");
                
    }
    
    public void tampil(){
        DefaultTableModel table1=new DefaultTableModel();
        table1.addColumn("no_akun1");
        table1.addColumn("nama_akun1");
        table1.addColumn("kd_posisi");


        tabel_golongan.setModel(table1);
        try{
            ResultSet res = koneksi1.statement.executeQuery("Select * from golongan");
            while(res.next()){
            table1.addRow(new Object[]{
                res.getString("no_akun1"),
                res.getString("nama_akun1"),
                res.getString("kd_posisi"),

            });
            tabel_golongan.setModel(table1);}
        }catch (Exception e){

       }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        text_noakun1 = new javax.swing.JTextField();
        text_namaakun1 = new javax.swing.JTextField();
        text_kdposisi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_golongan = new javax.swing.JTable();
        btn_kembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NO AKUN 1");

        jLabel2.setText("NAMA AKUN 1");

        jLabel3.setText("KD POSISI");

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hapus.png"))); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        text_noakun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_noakun1ActionPerformed(evt);
            }
        });

        tabel_golongan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tabel_golongan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_golonganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_golongan);

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        btn_kembali.setText("KEMBALI");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel4.setText("BAGAN GOLONGAN");

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1331, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_kdposisi)
                                    .addComponent(text_namaakun1)
                                    .addComponent(text_noakun1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_hapus)
                                        .addGap(34, 34, 34)
                                        .addComponent(btn_edit))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btn_simpan)
                                        .addGap(85, 85, 85)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_kembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kembali)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(text_noakun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_simpan)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(text_namaakun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(text_kdposisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_hapus)
                            .addComponent(btn_edit))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        frm_utama n = new frm_utama();
        n.setVisible(true);
        this.setVisible(false); // agar form yang tampil 1=fals
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
         String no_akun1 = text_noakun1.getText();
        String nama_akun1 = text_namaakun1.getText();
        String kd_posisi = text_kdposisi.getText();
        
        String SQL ="insert into golongann(no_akun1, nama_akun1, kd_posisi) values ('"+no_akun1+"','"+nama_akun1+"',"
                + "'"+kd_posisi+"')";
        System.out.println(SQL);
        tampil();
        clear();
        try {
            koneksi1.statement.executeUpdate(SQL);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Ditambahkan");
            tampil();
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data gagal Ditambahkan");
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Menghapus Data?","Delete",JOptionPane.YES_NO_OPTION );
        if (p==0){
        String no_akun1 = text_noakun1.getText();
        String nama_akun1 = text_namaakun1.getText();
        String kd_posisi  = text_kdposisi.getText();
     
        String SQL = "delete from akun where no_akun1='"+text_noakun1.getText()+"'";
                
        System.out.println(SQL);
        tampil();
        clear();
        
        try {
            koneksi1.statement.executeUpdate(SQL);
            tampil();
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        String no_akun1 = text_noakun1.getText();
        String nama_akun1 = text_namaakun1.getText();
        String kd_posisi = text_kdposisi.getText();
        
        String SQL = "UPDATE golongan SET "
                +"nama_akun1='"+text_namaakun1.getText()+"'"
                +"WHERE no_akun1='"+text_noakun1.getText()+"'";
        
        
        System.out.println(SQL);
        tampil();
        clear();
        try {
            koneksi1.statement.executeUpdate(SQL);
            tampil();
            JOptionPane.showMessageDialog(rootPane, "DATA AKUN BERHASIL GANTI");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, "DATA AKUN GAGAL DIGANTI");
        }
        
    }//GEN-LAST:event_btn_editActionPerformed

    private void tabel_golonganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_golonganMouseClicked
        // TODO add your handling code here:
             int table=tabel_golongan.getSelectedRow();
     String a=tabel_golongan.getValueAt(table, 0).toString();
     String b=tabel_golongan.getValueAt(table, 1).toString();
     String c=tabel_golongan.getValueAt(table, 2).toString();
     
     text_noakun1.setText(a);
     text_namaakun1.setText(b);
     text_kdposisi.setText(c);
    }//GEN-LAST:event_tabel_golonganMouseClicked

    private void text_noakun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_noakun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_noakun1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_input_golongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_input_golongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_input_golongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_input_golongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_input_golongan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_golongan;
    private javax.swing.JTextField text_kdposisi;
    private javax.swing.JTextField text_namaakun1;
    private javax.swing.JTextField text_noakun1;
    // End of variables declaration//GEN-END:variables
}
