package olahraga;

import static java.lang.String.format;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 0CIL650
 */
public class frm_input_jurnal_umum extends javax.swing.JFrame {
DefaultTableModel model;
    /**
     * Creates new form frm_input_jurnal_umum
     */
koneksi koneksi1 = new koneksi();

    public frm_input_jurnal_umum() {
        initComponents();
        String[] field={"tgl","ref","no_akun2","nama_akun2","kredit","debit"};
        model = new DefaultTableModel(field, 0);
        tabel_jurnal_umum.setModel(model);
        tampil();
    
    }
    
    public void clear(){
        text_tanggal.setText("");
        text_ref.setText("");
        text_no_akun2.setText("");
        text_nama_akun2.setText("");
        text_kredit.setText("");
        text_debit.setText("");
    
    }
    
    public void hapus(){
        int pilih = JOptionPane.showConfirmDialog(null, "APA ANDA YAKIN DIHAPUS?");
        if(pilih == JOptionPane.OK_OPTION)
            JOptionPane.showConfirmDialog(null, "DATA HILANG");
        else if(pilih == JOptionPane.NO_OPTION)
            JOptionPane.showConfirmDialog(null, "Anda Yakin?");
                
    }
    
    public void tampil(){
        DefaultTableModel table1=new DefaultTableModel();
        table1.addColumn("tanggal");
        table1.addColumn("ref");
        table1.addColumn("no_akun2");
        table1.addColumn("nama_akun2");
        table1.addColumn("kredit");
        table1.addColumn("debit");


        tabel_jurnal_umum.setModel(table1);
        try{
            ResultSet res = koneksi1.statement.executeQuery("Select * from jurnal_umum");
            while(res.next()){
            table1.addRow(new Object[]{
                res.getString("tgl"),
                res.getString("ref"),
                res.getString("no_akun2"),
                res.getString("nama_akun2"),
                res.getString("kredit"),
                res.getString("debit"),

            });
            tabel_jurnal_umum.setModel(table1);}
        }catch (Exception e){

       }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_kembali = new javax.swing.JButton();
        text_ref = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_jurnal_umum = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        text_debit = new javax.swing.JTextField();
        text_kredit = new javax.swing.JTextField();
        text_no_akun2 = new javax.swing.JTextField();
        text_nama_akun2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        text_tanggal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        btn_kembali.setText("KEMBALI");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        text_ref.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setText("TANGGAL");

        jLabel2.setText("REF");

        jLabel3.setText("NO AKUN2");

        jLabel4.setText("NAMA AKUN2");

        jLabel5.setText("DEBET");

        jLabel6.setText("#untuk_di_JurnaUmum_dikosongkan");

        tabel_jurnal_umum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", "", ""
            }
        ));
        tabel_jurnal_umum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_jurnal_umumMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_jurnal_umum);

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hapus.png"))); // NOI18N
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btn_ubah.setText("UBAH");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Kalinga", 1, 48)); // NOI18N
        jLabel7.setText("JURNAL UMUM");

        jLabel8.setText("KREDIT");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel9.setText("FORMAT = TAHUN-BULAN-HARI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(btn_kembali)
                            .addComponent(jLabel1))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_ref, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(text_no_akun2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(text_nama_akun2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_debit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(109, 109, 109)
                                .addComponent(btn_ubah))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_kredit, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btn_simpan)
                                .addGap(18, 18, 18)
                                .addComponent(btn_hapus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 64, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_kembali)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(text_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(text_ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text_no_akun2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_nama_akun2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ubah))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(text_debit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(text_kredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_simpan)
                            .addComponent(btn_hapus))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        frm_utama n = new frm_utama();
        n.setVisible(true);
        this.setVisible(false); // agar form yang tampil 1=fals
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        String tgl = text_tanggal.getText();
        String ref = text_ref.getText();
        String no_akun2 = text_no_akun2.getText();
        String nama_akun2 = text_nama_akun2.getText();
        String kredit = text_kredit.getText();
        String debit = text_debit.getText();
        
       String SQL ="insert into jurnal_umum(tgl,ref, no_akun2, nama_akun2, kredit, debit) values ('"+tgl+"','"+ref+"','"+no_akun2+"','"+nama_akun2+"',"
                + "'"+kredit+"','"+debit+"')";
       
        System.out.println(SQL);
        clear();
        tampil();
        
        try {
            koneksi1.statement.executeUpdate(SQL);
            JOptionPane.showMessageDialog(rootPane, "DATA BERHASIL DITAMBAHKAN");
            tampil();
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "DATA GAGAL DITAMBAHKAN");
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Menghapus Data?","Delete",JOptionPane.YES_NO_OPTION );
        if (p==0){
            String tgl = text_tanggal.getText();
        String ref = text_ref.getText();
        String no_akun2 = text_no_akun2.getText();
        String nama_akun2 = text_nama_akun2.getText();
        String kredit  = text_kredit.getText();
        String debit  = text_debit.getText();
     
        String SQL = "delete from jurnal_umum where no_akun2='"+text_no_akun2.getText()+"' "
                +"AND tgl='"+text_tanggal.getText()+"'";
                
        System.out.println(SQL);
        clear();
        tampil();
        
        
        try {
            koneksi1.statement.executeUpdate(SQL);
            tampil();
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        String tgl = text_tanggal.getText();
        String ref = text_ref.getText();
        String no_akun2 = text_no_akun2.getText();
        String nama_akun2 = text_nama_akun2.getText();
        String kredit  = text_kredit.getText();
        String debit  = text_debit.getText();
        
        String SQL = "UPDATE jurnal_umum SET "
                +"tgl='"+text_tanggal.getText()+"',"
                +"no_akun2='"+text_no_akun2.getText()+"',"
                +"nama_akun2='"+text_nama_akun2.getText()+"',"
                +"debit='"+text_debit.getText()+"',"
                +"kredit='"+text_kredit.getText()+"'"
                +" WHERE tgl='"+text_tanggal.getText()+"'"
                +" AND no_akun2='"+text_no_akun2.getText()+"'";
        
        
        System.out.println(SQL);
        tampil();
        clear();
        try {
            koneksi1.statement.executeUpdate(SQL);
            tampil();
            JOptionPane.showMessageDialog(rootPane, "DATA BERHASIL DIGANTI");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, "DATA AKUN GAGAL DIGANTI");
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void tabel_jurnal_umumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_jurnal_umumMouseClicked
        // TODO add your handling code here:
        int table=tabel_jurnal_umum.getSelectedRow();
     String a=tabel_jurnal_umum.getValueAt(table, 0).toString();
     String b=tabel_jurnal_umum.getValueAt(table, 1).toString();
     String c=tabel_jurnal_umum.getValueAt(table, 2).toString();
     String d=tabel_jurnal_umum.getValueAt(table, 3).toString();
     String e=tabel_jurnal_umum.getValueAt(table, 4).toString();
     String f=tabel_jurnal_umum.getValueAt(table, 5).toString();

     text_tanggal.setText(a);
     text_ref.setText(b);
     text_no_akun2.setText(c);
     text_nama_akun2.setText(d);
     text_kredit.setText(e);
     text_debit.setText(f);
     
    }//GEN-LAST:event_tabel_jurnal_umumMouseClicked

    private void jDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDatePropertyChange
        // TODO add your handling code here:
        tanggal();
    }//GEN-LAST:event_jDatePropertyChange

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    String tgl_jurnal;
    public void tanggal() {
 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_input_jurnal_umum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_input_jurnal_umum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_input_jurnal_umum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_input_jurnal_umum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_input_jurnal_umum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_jurnal_umum;
    private javax.swing.JTextField text_debit;
    private javax.swing.JTextField text_kredit;
    private javax.swing.JTextField text_nama_akun2;
    private javax.swing.JTextField text_no_akun2;
    private javax.swing.JTextField text_ref;
    private javax.swing.JTextField text_tanggal;
    // End of variables declaration//GEN-END:variables
}
